### ISSUE TITLE
doesn't work for me on emacs 24

### ISSUE THREAD

**Issue by hiredman** [juergenhoetzel/emacs-nexus#1]
http://repository.sonatype.org/service/local/data_index?q=commons
Contacting host: repository.sonatype.org:80
nnrss: Failed to fetch http://repository.sonatype.org/service/local/data_index?q=commons
setq: Wrong type argument: listp, "nnrss: Failed to fetch http://repository.sonatype.org/service/local/data_index?q=commons"
Mark set

**Comment by juergenhoetzel** [comment]
Could you please provide the output of your 
`*URL-DEBUG*` buffer?

**Comment by hiredman** [comment]
I don't have one, so I am unable to

**Comment by juergenhoetzel** [comment]
Please ensure `debug-on-error`  and  `url-debug`  is set to `t` , so you can provide the stacktrace and `*URL-DEBUG*` buffer.

**Comment by zcjava** [comment]
> Please ensure `debug-on-error` and `url-debug` is set to `t` , so you can provide the stacktrace and `*URL-DEBUG*` buffer.

i have the problem.  
![image](https://user-images.githubusercontent.com/1551382/132027812-eb4862b9-e8f2-4e12-9cff-837b7cb32f0e.png)

![image](https://user-images.githubusercontent.com/1551382/132027880-68dbd559-6b81-43cd-83da-1f123aa0e9a6.png)

sometime is error :
Debugger entered--Lisp error: (void-function   remove-if-not. 
remove-if-not not found

**Comment by zcjava** [comment]
please fix it . i need it very much .

**Comment by zcjava** [comment]
> http://repository.sonatype.org/service/local/data_index?q=commons
> Contacting host: repository.sonatype.org:80
> nnrss: Failed to fetch http://repository.sonatype.org/service/local/data_index?q=commons
> setq: Wrong type argument: listp, "nnrss: Failed to fetch http://repository.sonatype.org/service/local/data_index?q=commons"
> Mark set

hi guys, are you fixed it

**Comment by zcjava** [comment]
nexus--search-coordinates-internal: Symbol’s function definition is void: remove-if-not

**Comment by juergenhoetzel** [comment]
> 

Should be fixed by #2 

I also added Github Actions CI: Byte compiles on Emacs 24.5 (https://github.com/juergenhoetzel/emacs-nexus/actions/runs/1198903043)

Could you please test the master branch on your setup?

**Comment by zcjava** [comment]
wait a moment, i try it .

**Comment by zcjava** [comment]
> > 
> 
> Should be fixed by #2
> 
> I also added Github Actions CI: Byte compiles on Emacs 24.5 (https://github.com/juergenhoetzel/emacs-nexus/actions/runs/1198903043)
> 
> Could you please test the master branch on your setup?

thx, is ok now. please push it to elpa.
btw: i have other question:
use ac-nexus. but version donnot code complete?
u have plan  to solve it

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/132049023-34d65f10-e75a-4ff7-b47f-49fe7312b576.png)

**Comment by zcjava** [comment]
i use company to code completion.  how change auto-complete to company mode . have function?

**Comment by juergenhoetzel** [comment]
> thx, is ok now. please push it to elpa.
Its available on [melpa](https://melpa.org/)

> btw: i have other question:
> use ac-nexus. but version donnot code complete?
> u have plan to solve it
> i use company to code completion. how change auto-complete to company mode . have function?

It seems you are using a plain maven `pom.xml`file.  `ac-nexus` only supports Leiningen `project.clj` at the moment.
I just checked

```elisp
(package-install 'auto-complete)
(require 'ac-nexus)
(add-hook 'clojure-mode-hook 'ac-source-lein-set-up)
```
`company`provides a `auto-complete`backend. So it works out-of-the-box.

To be honest, the code originated as a quick hack for my Clojure projects 10 Years ago :fearful: .

Leiningen itself has fallen behind a bit. It should be easy to adapt the code also for `deps.edn`Clojure projects and general  `pom.xml` files.

Also it should use builtin `completion-at-point` functions instead of requiring  the  3rd party-package `auto-complete`.

I will create a seperate completion issue.
